import { createCanvas } from "canvas";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { pool } from "../config/database.js";

// Get __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Generate summary image with country statistics
async function generateSummaryImage() {
  try {
    // Fetch data for the image
    const [metadata] = await pool.execute(
      "SELECT total_countries, last_refreshed_at FROM refresh_metadata WHERE id = 1"
    );

    const [topCountries] = await pool.execute(
      "SELECT name, estimated_gdp FROM countries WHERE estimated_gdp IS NOT NULL ORDER BY estimated_gdp DESC LIMIT 5"
    );

    if (metadata.length === 0) {
      throw new Error("No metadata found");
    }

    // Create canvas
    const width = 800;
    const height = 600;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext("2d");

    // Background
    ctx.fillStyle = "#1a1a2e";
    ctx.fillRect(0, 0, width, height);

    // Title
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 32px Arial";
    ctx.fillText("Country Data Summary", 50, 60);

    // Total countries
    ctx.font = "24px Arial";
    ctx.fillStyle = "#00d9ff";
    ctx.fillText(`Total Countries: ${metadata[0].total_countries}`, 50, 120);

    // Last refreshed
    ctx.fillStyle = "#ffaa00";
    const lastRefresh = new Date(
      metadata[0].last_refreshed_at
    ).toLocaleString();
    ctx.fillText(`Last Refreshed: ${lastRefresh}`, 50, 160);

    // Top 5 countries header
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 26px Arial";
    ctx.fillText("Top 5 Countries by Estimated GDP", 50, 230);

    // Draw top 5 countries
    ctx.font = "20px Arial";
    let yPosition = 280;

    topCountries.forEach((country, index) => {
      ctx.fillStyle = "#00ff88";
      const gdpFormatted = country.estimated_gdp
        ? `$${country.estimated_gdp.toLocaleString("en-US", {
            maximumFractionDigits: 2,
          })}`
        : "N/A";

      ctx.fillText(
        `${index + 1}. ${country.name}: ${gdpFormatted}`,
        70,
        yPosition
      );

      yPosition += 50;
    });

    // Footer
    ctx.fillStyle = "#888888";
    ctx.font = "16px Arial";
    ctx.fillText("Generated by Country API System", 50, height - 30);

    // Save image to cache directory
    const cacheDir = path.join(__dirname, "../../cache");
    if (!fs.existsSync(cacheDir)) {
      fs.mkdirSync(cacheDir, { recursive: true });
    }

    const imagePath = path.join(cacheDir, "summary.png");
    const buffer = canvas.toBuffer("image/png");
    fs.writeFileSync(imagePath, buffer);

    console.log("✅ Summary image generated successfully");
  } catch (error) {
    console.error("❌ Image generation failed:", error.message);
    throw error;
  }
}

export { generateSummaryImage };
